const level1 = new Level(
    [
        new Bear(),
        new Mage(),
        new Ooze(),
        new BossDemon()
    ],
    [
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/8.png', -719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/7.png', -719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/6.png', -719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/5.png', -719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/4.png', -719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/3.png', -719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/2.png', -719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/1.png', -719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/8.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/7.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/6.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/5.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/4.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/3.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/2.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/1.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/8.png', 719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/7.png', 719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/6.png', 719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/5.png', 719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/4.png', 719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/3.png', 719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/2.png', 719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/1.png', 719),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/8.png', 1439),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/7.png', 1439),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/6.png', 1439),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/5.png', 1439),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/4.png', 1439),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/3.png', 1439),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/2.png', 1439),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/1.png', 1439),
    ],
    [
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', -96, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', -64, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', -32, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 0, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 32, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 64, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 96, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 128, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 160, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 192, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 224, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 256, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 288, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 320, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 352, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 384, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 416, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 448, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 480, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 512, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 544, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 576, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 608, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 640, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 672, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 704, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 736, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 768, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 800, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 832, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 864, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 896, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 928, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 960, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 992, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1024, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1056, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1088, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1120, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1152, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1184, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1216, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1248, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1280, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1312, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1344, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1376, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1408, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1440, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1472, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1504, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1536, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1568, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1600, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1632, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1664, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1696, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1728, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1760, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1792, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1824, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1856, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1888, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1920, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1952, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 1984, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 2016, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 2048, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 2080, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 2112, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 2144, 448, 32, 32),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 2160, 448, 32, 32),
    ]

);