const level1 = new Level(
    [
        new Bear(),
        new Mage(),
        new Ooze(),
        new RedMonster(),
        new TinyMonster(),
        new YellowMonster(),
        new Bear(),
        new Mage(),
        new Ooze(),
        new RedMonster(),
        new TinyMonster(),
        new YellowMonster()
    ],
    [
        new Food(),
        new Food(),
        new Food(),
        new Food(),
        new Food(),
        new Food(),
        new Food(),
        new Food(),
        new Food(),
        new Food(),
    ],
    [
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/8.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/7.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/6.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/5.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/4.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/3.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/2.png', 0),
        new Background('./assets/img/platformer-pixel-art-tileset/Background/Layers/1.png', 0)
    ],
    [
        new AnimatedObjects('coin', 510, 397),
        new AnimatedObjects('coin', 561, 397),
        new AnimatedObjects('coin', 612, 397),
        new AnimatedObjects('coin', 663, 397),
        new AnimatedObjects('coin', 1179, 397),
        new AnimatedObjects('coin', 1230, 346),
        new AnimatedObjects('coin', 1281, 295),
        new AnimatedObjects('coin', 1332, 270),
        new AnimatedObjects('coin', 1383, 270),
        new AnimatedObjects('coin', 1434, 295),
        new AnimatedObjects('coin', 1485, 346),
        new AnimatedObjects('coin', 1536, 397),
        new AnimatedObjects('coin', 2142, 346),
        new AnimatedObjects('coin', 2193, 346),
        new AnimatedObjects('coin', 2244, 346),
        new AnimatedObjects('coin', 2295, 346),
        new AnimatedObjects('coin', 3380, 270),
        new AnimatedObjects('coin', 3432, 270),
        new AnimatedObjects('coin', 3484, 270),
        new AnimatedObjects('coin', 3536, 270),
        new AnimatedObjects('coin', 3588, 270),
        new AnimatedObjects('coin', 3640, 270),
        new AnimatedObjects('coin', 5096, 397),
        new AnimatedObjects('coin', 5148, 397),
        new AnimatedObjects('coin', 5200, 397),
        new AnimatedObjects('coin', 5252, 397),
        new AnimatedObjects('coin', 5304, 397),
        new AnimatedObjects('coin', 5356, 397),
        new AnimatedObjects('coin', 5408, 397),
        new AnimatedObjects('coin', 5460, 397),
        new AnimatedObjects('coin', 5512, 397),
        new AnimatedObjects('coin', 5564, 397),
        new AnimatedObjects('coin', 6762, 397),
        new AnimatedObjects('coin', 6762, 346),
        new AnimatedObjects('coin', 6762, 295)
    ],
    [
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree2.png', 275, 300, 154, 102),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree3.png', 730, 252, 102, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 740, 303, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree_Back2.png', 1200, 125, 154, 102),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass2_2.png', 1235, 230, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree1.png', 1950, 300, 154, 102),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree_Back1.png', 2580, 300, 154, 102),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree2.png', 2530, 300, 154, 102),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree2.png', 2630, 300, 154, 102),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree_Back2.png', 5690, 125, 154, 102),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass2_2.png', 5725, 230, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree1.png', 3180, 300, 154, 102),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree_Back1.png', 4250, 125, 154, 102),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass2_2.png', 4280, 228, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree3.png', 4635, 252, 102, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 4645, 303, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree3.png', 6245, 252, 102, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 6255, 303, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Trees/Tree_Back3.png', 6345, 201, 102, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 6355, 252, 51, 51),

        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 510, 397, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 561, 397, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 612, 397, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 663, 397, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass4_1.png', 540, 397, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass4_1.png', 590, 397, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass4_1.png', 640, 397, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass4_1.png', 5020, 397, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 1670, 397, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Grass/Grass5_1.png', 1720, 397, 51, 51),
        new AnimatedObjects('flag', 7100, 397)
    ],
    [
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Spikes/Spikes1_2.png', 1695, 398, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Spikes/Spikes1_2.png', 2300, 398, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Spikes/Spikes1_2.png', 3430, 398, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Spikes/Spikes1_2.png', 3600, 398, 51, 51),
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Objects/Spikes/Spikes1_2.png', 5050, 398, 51, 51),
    ],
    [
        new BackgroundObjects('./assets/img/platformer-pixel-art-tileset/Tiles/Tileset/TileSet_02.png', 0, 448, 32, 32)
    ]
);